import type { Metadata } from "next";
import '../../public/assets/styles/sass/main.scss'
import Header from "./components/Header";
import { Roboto } from "next/font/google";
import MUIProvider from "./components/provider/MUIProvider";
import { Box } from "@mui/material";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["vietnamese"],
  variable: "--font-roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <MUIProvider>
        <Header />
        <Box sx={{ minHeight: '100vh', backgroundColor: 'background.default', padding: '16px' }}>
            {children}
        </Box>
        <Footer/>
        </MUIProvider>
      </body>
    </html>
  );
}
